name: Build image on push or PR
on: [ "push"]

jobs:
    build:

        runs-on: ubuntu-18.04
        
        steps:
        - name: Create release draft
          uses: softprops/action-gh-release@v1
          with:
            files: |
              ${{ env.IMAGE_NAME }}.zip
            name: ${{ github.ref }}
            draft: true
            body: ${{ fromJson(steps.get_last_release.outputs.data).body }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
