name: Automatically Build image on tag ONLY
on:
    push:
        tags:
          - v[0-9]+.[0-9]+.[0-9]+
          - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
    build:

        runs-on: ubuntu-18.04
        
        steps:
        
        - uses: actions/checkout@v1

        - name: Run Apt-get update
          run: sudo apt-get update

        - name: Install dependencies
          run: sudo apt-get -y install quilt qemu-user-static debootstrap bsdtar

        - name: Nuke current Docker installation
          run: |
                sudo systemctl stop docker
                sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
                sudo rm -rf /var/lib/docker
        
        - name: Re-install Docker
          run: |
                curl -fsSL https://get.docker.com -o get-docker.sh
                sudo sh get-docker.sh
                docker --version

        - name: Enable experimental features in Docker
          run: |
                sudo rm -rf /etc/docker/daemon.json
                echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
                sudo systemctl restart docker
        
        - name: Set image name
          run: |
                UMBREL_OS_VERSION="$(git describe --tags)"
                IMAGE_NAME="umbrel-os-${UMBREL_OS_VERSION}"
                echo "UMBREL_OS_VERSION=$UMBREL_OS_VERSION"  >> $GITHUB_ENV
                echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

        - name: Run build script
          run: |
                echo "Building $IMAGE_NAME"
                sudo IMG_FILENAME=$IMAGE_NAME ZIP_FILENAME=$IMAGE_NAME UMBREL_OS_VERSION=$UMBREL_OS_VERSION ./build.sh

        - name: Copy ZIP to current working dir
          run: cp deploy/*.zip ./

        - name: Debug current working dir
          run: ls -la
 
        - name: "Get latest Umbrel release from the GitHub API"
          uses: octokit/request-action@v2.x
          id: get_last_release
          with:
            route: POST /repos/{owner}/{repo}/releases/latest
            owner: getumbrel
            repo: umbrel
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create release draft
          uses: softprops/action-gh-release@v1
          with:
            files: |
              ${{ env.IMAGE_NAME }}.zip
            name: ${{ github.ref }}
            draft: true
            body: ${{ fromJson(steps.get_last_release.outputs.data).body }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
